name: Deploy React App
on:
  push:
    branches:
      - develop
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Code
        uses: actions/checkout@v3
      - name: Install Node v18
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install
        run: npm install
      - name: build
        run: | 
          npm run build
          cp .htaccess build/
          sshpass -p "root12345ROOT" scp -r ./build rootMoses@4.246.133.113:/home/rootMoses/apps/